apiVersion: apps/v1
kind: Deployment
metadata:
  name: foreningsregister-api
  labels:
    app: foreningsregister-api
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foreningsregister-api
  template:
    metadata:
      labels:
        app: foreningsregister-api
        component: api
spec:
      initContainers:
      - name: migrate-db
        image: foreningsregister/api:latest
        command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: database-url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      containers:
      - name: api
        image: foreningsregister/api:latest
        ports:
        - containerPort: 3000
          name: http
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: database-url
        resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1001
