apiVersion: v1
kind: Service
metadata:
  name: foreningsregister-api
  labels:
    app: foreningsregister-api
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: foreningsregister-api
