apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgresql
    component: database
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded values
  username: cG9zdGdyZXM= # postgres
  password: c3VwZXJfc2VjcmV0X3Bhc3N3b3Jk # super_secret_password
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnN1cGVyX3NlY3JldF9wYXNzd29yZEBwb3N0Z3Jlc3FsOjU0MzIvZm9yZW5pbmdzcmVnaXN0ZXI= # postgresql://postgres:super_secret_password@postgresql:5432/foreningsregister
