apiVersion: v1
kind: Service
metadata:
  name: foreningsregister-frontend
  labels:
    app: foreningsregister-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: foreningsregister-frontend
