apiVersion: apps/v1
kind: Deployment
metadata:
  name: foreningsregister-api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: NODE_ENV
              value: 'production'
