---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: foreningsregister
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: foreningsregister-git-secret
  url: ssh://git@github.com/yourusername/foreningsregister.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: foreningsregister-production
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: foreningsregister
  targetNamespace: foreningsregister-prod
  timeout: 5m0s
  wait: true
  postBuild:
    substitute:
      CLUSTER_ENV: 'production'
      CLUSTER_NAME: 'production-cluster'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: foreningsregister-api
  namespace: flux-system
spec:
  image: ghcr.io/yourusername/foreningsregister/api
  interval: 1m0s
  secretRef:
    name: ghcr-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: foreningsregister-frontend
  namespace: flux-system
spec:
  image: ghcr.io/yourusername/foreningsregister/frontend
  interval: 1m0s
  secretRef:
    name: ghcr-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: foreningsregister-production
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: foreningsregister
  git:
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: |
        chore: update production images

        {{range .Updated.Images}}
        - {{.}}
        {{end}}
  update:
    path: ./k8s/overlays/production
    strategy: Setters
