apiVersion: apps/v1
kind: Deployment
metadata:
  name: foreningsregister-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: NODE_ENV
              value: 'staging'
