apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../bases

namespace: foreningsregister-staging

namePrefix: staging-

commonAnnotations:
  environment: staging
  managed-by: kustomize

patchesStrategicMerge:
  - api-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - postgresql-pvc.yaml

images:
  - name: foreningsregister/api
    newTag: staging-latest
  - name: foreningsregister/frontend
    newTag: staging-latest
